version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: news-chatbot-redis-dev
    ports:
      - "6379:6379"
    networks:
      - news-chatbot-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: news-chatbot-backend-dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - JINA_API_KEY=${JINA_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - news-chatbot-network
    command: npm run dev

networks:
  news-chatbot-network:
    driver: bridge